project_id = "nabodbmvfrhhrjeiiimm"

[functions.approve-benutzer]
verify_jwt = true

[functions.assign-employee-to-customer]
verify_jwt = true

[functions.delete-mitarbeiter]
verify_jwt = true

[functions.reject-benutzer]
verify_jwt = true

[functions.parse-appointment-text]
verify_jwt = false
