// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nabodbmvfrhhrjeiiimm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hYm9kYm12ZnJoaHJqZWlpaW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTgzMTYsImV4cCI6MjA3MDIzNDMxNn0.jHwzpKUk4M-51dM8939kabSSAtn5ahtIWaYvEyftYeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});